# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae997231f129f3602c4f8421ac38d4c5a7569785d8f875cbfef2f24a6e924158c63a73a85b33b2a410b2640d32eb88af89d3f227031529146f06243ddfb9732b

test:
  secret_key_base: c0b78d3f73b309e10689ac0a84b70ccbca07842ffe6d446f4af5b3882bad76eafb77c8d484c2a6090924c76312d57887ae062970fee2d3fa8e1afbe78bf90857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
